name: lichhoc
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.2
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  crypto: ^3.0.3
  excel: ^4.0.3
  flutter:
    sdk: flutter

  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
